ARG BASE_IMAGE=debian:bookworm
FROM ${BASE_IMAGE}

COPY ubuntu-archive-ca.crt /etc/ssl/certs/ca-certificates.crt
COPY apt-network.conf /etc/apt/apt.conf.d/80-ci-network
RUN find /etc/apt -type f \( -name '*.list' -o -name '*.sources' \) \
    -exec sed -i 's|http://|https://|g' '{}' +
COPY install-debian-build-deps.sh /usr/local/bin/
RUN /usr/local/bin/install-debian-build-deps.sh
